"""
Schemas package - Pydantic DTOs.
"""
from app.schemas.user import (
    UserBase,
    UserRegisterDTO,
    UserLoginDTO,
    UserUpdateDTO,
    UserResponse,
    UserBriefResponse,
    Token,
    TokenData,
)
from app.schemas.course import (
    ModuleCreateDTO,
    ModuleResponse,
    LessonCreateDTO,
    LessonResponse,
    LessonBriefResponse,
    QuizQuestionCreateDTO,
    QuizQuestionResponse,
    QuizCreateDTO,
    QuizResponse,
    QuizSubmitDTO,
    QuizAttemptResponse,
    CourseCreateDTO,
    CourseUpdateDTO,
    CourseResponse,
    CourseDetailResponse,
    CourseBriefResponse,
    EnrollmentCreateDTO,
    EnrollmentResponse,
    EnrollmentProgressDTO,
    CertificateResponse,
    TransactionResponse,
)

__all__ = [
    # User schemas
    "UserBase",
    "UserRegisterDTO",
    "UserLoginDTO", 
    "UserUpdateDTO",
    "UserResponse",
    "UserBriefResponse",
    "Token",
    "TokenData",
    # Course schemas
    "ModuleCreateDTO",
    "ModuleResponse",
    "LessonCreateDTO",
    "LessonResponse",
    "LessonBriefResponse",
    "QuizQuestionCreateDTO",
    "QuizQuestionResponse",
    "QuizCreateDTO",
    "QuizResponse",
    "QuizSubmitDTO",
    "QuizAttemptResponse",
    "CourseCreateDTO",
    "CourseUpdateDTO",
    "CourseResponse",
    "CourseDetailResponse",
    "CourseBriefResponse",
    "EnrollmentCreateDTO",
    "EnrollmentResponse",
    "EnrollmentProgressDTO",
    "CertificateResponse",
    "TransactionResponse",
]
